### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by hapit** [jambit/Azubi-Onboardingphase-2019-AlexJovan#1]
4,1,2,3 erzeugt einen Fehler. Hier meine Ausgabe:
```
➜  AlexJovanMassaker git:(develop) ✗ ./gradlew run --console=plain
> Task :compileJava UP-TO-DATE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE

> Task :run
You wake up on the floor, everything is dark
Your back hurts, you feel very nausea's because you hadn't eaten in days.
You feel the dryed blood on your clothes sticking to your skin.
You decide to stand up and check how bad your Injuries are.
In the moment you try to stand up you drop to the ground in an instant and you feel how the complete room you are in is moving up.
Two doors open in front of you letting Light comes through the little crack between them.
Your eyes close themselves very quickly and they feel like this is the first time Light touched them
While the Light is burning in your eyes you try to escape from the darkness you were in before
Now that you have left the dark room you can clearly see that you were trapped in an elevator without electricity
You dont even want to start wondering about how the elevator couldn't move but you have electricity in the new room you are in
You are too occupied with the fact that you have lost your memory and that your head is bleeding very badly
But there is hope you think while you see a woman walking to something like a reception but you cant reach her because a glass door is seperating you both and you dont know how to open it
Try to opening the door
---MENU---
current room: elevatorroom
HP: 100
[1] Change Room
[2] Interact list
[3] Inventory
[4] Look around you
4
You see a key-card on the ground
[1] Pick up and use key-card
[2] Leave key-card search other way
1
Congratulations you have opened the locked door, now you step into a big room that looks like a reception



---MENU---
current room: reception
HP: 100
[1] Change Room
[2] Interact list
[3] Inventory
2
[0] Exit
3
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at com.jambit.game.Player.playerInteractMenu(Player.java:63)
	at com.jambit.game.Player.playerMenu(Player.java:84)
	at com.jambit.game.Player.onTick(Player.java:33)
	at com.jambit.Actor.tick(Actor.java:160)
	at com.jambit.Level.objectTick(Level.java:137)
	at com.jambit.Level.Tick(Level.java:33)
	at com.jambit.Core.mainLoop(Core.java:35)
	at com.jambit.Core.start(Core.java:26)
	at com.jambit.Main.main(Main.java:14)

> Task :run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/Users/phemmer/.sdkman/candidates/java/8.0.222-zulu/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 21s
2 actionable tasks: 1 executed, 1 up-to-date
```

**Comment by iceHtwoO** [comment]
In der neusten Version sollten diese Probleme zum großten Teil behoben sein. Danke für dein Feedback👍
